server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "102174127187-6t367sik1jdjk3a484ja97s3s1el1esp.apps.googleusercontent.com"
            client-secret: "${GOOGLE_CLIENT_SECRET}"
            redirect-uri: "http://localhost:8081/login/oauth2/code/google"
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            issuer-uri: https://accounts.google.com

